// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_Fk5v4BHW2Fpxm-O3DWBVHKglLSt5Dc',
    appId: '1:524100826492:web:52c94d4cac89fa049e20f9',
    messagingSenderId: '524100826492',
    projectId: 'flutter-my-app-9fea1',
    authDomain: 'flutter-my-app-9fea1.firebaseapp.com',
    storageBucket: 'flutter-my-app-9fea1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkAO5KhhXBYMLmZ-MsmOig-3OeU06TeIQ',
    appId: '1:524100826492:android:d62394935c3870cd9e20f9',
    messagingSenderId: '524100826492',
    projectId: 'flutter-my-app-9fea1',
    storageBucket: 'flutter-my-app-9fea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SriJ3tO7e4bOJv2L43_luKK3ZoOSkOM',
    appId: '1:524100826492:ios:07f6332f1233b0359e20f9',
    messagingSenderId: '524100826492',
    projectId: 'flutter-my-app-9fea1',
    storageBucket: 'flutter-my-app-9fea1.appspot.com',
    iosClientId:
        '524100826492-kh9pr53euka1hbjmfd6q6lfecdgcjlo9.apps.googleusercontent.com',
    iosBundleId: 'com.callor.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8SriJ3tO7e4bOJv2L43_luKK3ZoOSkOM',
    appId: '1:524100826492:ios:37897b612766190d9e20f9',
    messagingSenderId: '524100826492',
    projectId: 'flutter-my-app-9fea1',
    storageBucket: 'flutter-my-app-9fea1.appspot.com',
    iosClientId:
        '524100826492-2rpcumjumli8st5c40cic8gsf4hjolds.apps.googleusercontent.com',
    iosBundleId: 'com.callor.firebase.RunnerTests',
  );
}
